Murodovich/entities homework taskresult taskresultfile video
Lazies-Team/LMS-test pull request #33
Opened 2024-02-09 18:57 UTC by murodovich

close #15  #28 #29 #30 #31 #32

2024-02-09 19:06 UTC, SardorSohinazarov approved these changes

2024-02-09 19:06 UTC, SardorSohinazarov commented on src/Domain/Entities/TaskResult.cs
> +        public TaskResultStatus
Error

2024-02-09 19:13 UTC, Berdikulov-571 approved these changes

2024-02-09 19:20 UTC, SardorSohinazarov requested changes

2024-02-09 19:20 UTC, SardorSohinazarov commented on src/Domain/Entities/HomeworkFile.cs
> +    }
Homework Navigation yo'q

2024-02-10 06:21 UTC, SardorSohinazarov approved these changes

2024-02-10 06:21 UTC, merged